name: carpool
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  overlay_support: ^2.1.0

  # Models
  freezed_annotation: 2.4.1
  json_serializable: 6.7.1
  json_annotation: 4.8.1

  cupertino_icons: ^1.0.2
  flutter_phoenix: ^1.1.1
  flutter_bloc: ^8.1.4
  hexagon: ^0.2.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_admin: ^0.2.0
  firebase_dart: ^1.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.8
  freezed: 2.4.7
  hive_generator: 2.0.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/strings/strings_en.json
    - assets/strings/strings_pt.json

